name: 幻水総選挙2020（スプレッドシート）

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  gensosenkyo_2020_spreadsheet:
    name: 幻水総選挙2020（スプレッドシート）
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18.12.1']
    steps:
      - name: コードをチェックアウトする
        uses: actions/checkout@v3
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: $ yarn install を行う
        run: yarn install
