name: 幻水総選挙2020（スプレッドシート）

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*.*.*'

jobs:
  gensosenkyo_2020_spreadsheet:
    name: 幻水総選挙2020（スプレッドシート）
    runs-on: ubuntu-latest
    steps:
      - name: コードをチェックアウトする
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Node.js のセットアップを行う
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: yarn
      - name: $ yarn install を行う
        run: yarn install
